# Generated by Django 4.2.3 on 2023-08-01 11:22

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('GENERAL_CHECKUP', 'General Checkup'), ('SPECIFIC_COMPLAINT', 'Specific Complaint')], max_length=250)),
                ('complaint_description', models.TextField(blank=True, null=True, verbose_name='Complaint Description')),
                ('complaint_image_1', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Complaint Image 1')),
                ('complaint_image_2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Complaint Image 2')),
                ('complaint_image_3', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Complaint Image 3')),
                ('complaint_video', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Complaint Video')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Vehicle Name')),
                ('type', models.CharField(choices=[('Oil Engines', 'Oil Engine'), ('Auto', 'Auto'), ('Bus', 'Bus'), ('Car', 'Car'), ('JCB Loader', 'JCB Loader'), ('Generator', 'Generator'), ('Marine Engines', 'Marine Engines'), ('Tractor', 'Tractor'), ('Tipper', 'Tipper'), ('6 wheel - Truck', '6 wheel - Truck'), ('10 wheel - Truck', '10 wheel - Truck'), ('12 wheel - Truck', '12 wheel - Truck'), ('Tanker Lorry', 'Tanker Lorry'), ('Van', 'Van'), ('Others', 'Others')], max_length=50, verbose_name='Vehicle Type')),
                ('application', models.CharField(choices=[('Agriculture', 'Agriculture'), ('Commercial', 'Commercial'), ('Domestic', 'Domestic')], max_length=255, verbose_name='Vehicle Application')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('Single Cyl- Pump', 'Single Cyl- Pump'), ('VE - Pump', 'VE - Pump'), ('Inline 6cyl - Pump', 'Inline 6cyl - Pump'), ('Inline 4cyl - Pump', 'Inline 4cyl - Pump'), ('Inline 3cyl - Pump', 'Inline 3cyl - Pump'), ('VE-EDC - Pump', 'VE-EDC - Pump'), ('CRDI - Pump', 'CRDI - Pump'), ('China - Pump', 'China - Pump'), ('Injectors only', 'Injectors Only'), ('CR-Injectors Only', 'CR-Injectors Only')], max_length=75, verbose_name='Component')),
                ('name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('mobile', models.IntegerField(verbose_name='Mobile')),
                ('alternate_mobile', models.IntegerField(blank=True, verbose_name='Alternate Mobile')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('service_booking_date', models.DateField(db_index=True, verbose_name='Booking Date')),
                ('service_type', models.CharField(choices=[('Quick Service', 'Quick Service'), ('Regular Service', 'Regular Service')], max_length=50)),
                ('complaint', models.ManyToManyField(blank=True, to='booking.complaint')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.vehicle')),
            ],
        ),
    ]
